### ISSUE TITLE
[BUG] Fix initial superuser account creation.

### ISSUE THREAD

**Issue by kovitikus** [kovitikus/hecate#37]
When refactoring the project's directory structure via #36 I came across an issue where the first account made has the OOC character typeclass as a normal `characters.characters.Character` typeclass and the equipment generation breaks after the inventory bag is created.

I need to track down the origin of how the first account character is made and fix its behavior.

**Comment by kovitikus** [comment]
I fixed the equipment generation in commit 3c96ded, but still need to address the typeclass.

Tracking down the issue it seems that the Prototype Spawner attempts to set the inventory bag's home to Limbo `dbref #2`, but Limbo isn't created yet when the initial superuser is made, so it fails.

```python
        if not self.dbref == '#1':
            self.equip.generate_equipment()
```

I instead generate equipment in `at_initial_setup` hook within `server/conf` by finding the superuser and then calling the method.
```python
    char = search_object('#1', use_dbref=True)[0]
    char.equip.generate_equipment()
```

This will address the traceback.
```
21-03-03 22:00:24-05 [..] Initial setup: Creating objects (Account #1 and Limbo room) ...
21-03-03 22:00:24-05 Unhandled Error
	Traceback (most recent call last):
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "d:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "d:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "d:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "d:\muddev\evennia\evennia\server\portal\amp.py", line 397, in makeConnection
	    amp.BinaryBoxProtocol.makeConnection(self, transport)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\protocols\amp.py", line 2394, in makeConnection
	    self.connectionMade()
	  File "d:\muddev\evennia\evennia\server\amp_client.py", line 116, in connectionMade
	    self.factory.server.run_initial_setup()
	  File "d:\muddev\evennia\evennia\server\server.py", line 353, in run_initial_setup
	    initial_setup.handle_setup(0)
	  File "d:\muddev\evennia\evennia\server\initial_setup.py", line 223, in handle_setup
	    setup_func()
	  File "d:\muddev\evennia\evennia\server\initial_setup.py", line 90, in create_objects
	    god_character = create.create_object(character_typeclass, key=god_account.username, nohome=True)
	  File "d:\muddev\evennia\evennia\utils\create.py", line 171, in create_object
	    new_object.save()
	  File "d:\muddev\evennia\evennia\utils\idmapper\models.py", line 442, in save
	    super().save(*args, **kwargs)
	  File "d:\muddev\evenv\Lib\site-packages\django\db\models\base.py", line 744, in save
	    force_update=force_update, update_fields=update_fields)
	  File "d:\muddev\evenv\Lib\site-packages\django\db\models\base.py", line 793, in save_base
	    update_fields=update_fields, raw=raw, using=using,
	  File "d:\muddev\evenv\Lib\site-packages\django\dispatch\dispatcher.py", line 175, in send
	    for receiver in self._live_receivers(sender)
	  File "d:\muddev\evenv\Lib\site-packages\django\dispatch\dispatcher.py", line 175, in <listcomp>
	    for receiver in self._live_receivers(sender)
	  File "d:\muddev\evennia\evennia\typeclasses\models.py", line 70, in call_at_first_save
	    instance.at_first_save()
	  File "d:\muddev\evennia\evennia\objects\objects.py", line 1132, in at_first_save
	    self.at_object_creation()
	  File ".\characters\characters.py", line 41, in at_object_creation
	    self.equip.generate_equipment()
	  File ".\characters\equipment_handler.py", line 31, in generate_equipment
	    basic_bag = spawn('inventory_bag')
	  File "d:\muddev\evennia\evennia\prototypes\spawner.py", line 919, in spawn
	    create_kwargs["db_home"] = init_spawn_value(val, value_to_obj)
	  File "d:\muddev\evennia\evennia\prototypes\prototypes.py", line 937, in init_spawn_value
	    value = validator(value)
	  File "d:\muddev\evennia\evennia\prototypes\prototypes.py", line 966, in value_to_obj
	    return dbid_to_obj(value, ObjectDB)
	  File "d:\muddev\evennia\evennia\utils\utils.py", line 757, in dbref_to_obj
	    return objclass.objects.get(id=dbid)
	  File "d:\muddev\evennia\evennia\utils\idmapper\manager.py", line 32, in get
	    inst = super().get(*args, **kwargs)
	  File "d:\muddev\evenv\Lib\site-packages\django\db\models\manager.py", line 82, in manager_method
	    return getattr(self.get_queryset(), name)(*args, **kwargs)
	  File "d:\muddev\evenv\Lib\site-packages\django\db\models\query.py", line 408, in get
	    self.model._meta.object_name
	evennia.objects.models.DoesNotExist: ObjectDB matching query does not exist.
```

**Comment by kovitikus** [comment]
```
21-03-06 03:21:43-05 Loading d:\muddev\evennia\evennia\server\server.py...
21-03-06 03:21:43-05 Loaded.
21-03-06 03:21:43-05 twistd 20.3.0 (d:\muddev\evenv\scripts\python.exe 3.7.4) starting up.
21-03-06 03:21:43-05 reactor class: twisted.internet.selectreactor.SelectReactor.
21-03-06 03:21:43-05 Webserver starting on 4005
21-03-06 03:21:43-05 [..] Initial setup: Creating objects (Account #1 and Limbo room) ...
21-03-06 03:21:43-05 [..] Initial setup: Creating default channels ...
21-03-06 03:21:43-05 [..] Initial setup: Running at_initial_setup() hook.
21-03-06 03:21:43-05 Unhandled Error
	Traceback (most recent call last):
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "d:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "d:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "d:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "d:\muddev\evennia\evennia\server\portal\amp.py", line 397, in makeConnection
	    amp.BinaryBoxProtocol.makeConnection(self, transport)
	  File "d:\muddev\evenv\Lib\site-packages\twisted\protocols\amp.py", line 2394, in makeConnection
	    self.connectionMade()
	  File "d:\muddev\evennia\evennia\server\amp_client.py", line 116, in connectionMade
	    self.factory.server.run_initial_setup()
	  File "d:\muddev\evennia\evennia\server\server.py", line 353, in run_initial_setup
	    initial_setup.handle_setup(0)
	  File "d:\muddev\evennia\evennia\server\initial_setup.py", line 223, in handle_setup
	    setup_func()
	  File "d:\muddev\evennia\evennia\server\initial_setup.py", line 165, in at_initial_setup
	    mod.at_initial_setup()
	  File "D:\muddev\hecate\server\conf\at_initial_setup.py", line 34, in at_initial_setup
	    room3 = create_object(typeclass='rooms.rooms.Room', key=f'{char.get_display_name()}\'s Office')
	builtins.TypeError: get_display_name() missing 1 required positional argument: 'looker'
	
21-03-06 03:21:44-05 [..] Server disconnected from the portal.
```

**Comment by kovitikus** [comment]
The traceback seems to be addressed.

```
21-03-06 03:36:34-05 Loading d:\muddev\evennia\evennia\server\server.py...
21-03-06 03:36:35-05 Loaded.
21-03-06 03:36:35-05 twistd 20.3.0 (d:\muddev\evenv\scripts\python.exe 3.7.4) starting up.
21-03-06 03:36:35-05 reactor class: twisted.internet.selectreactor.SelectReactor.
21-03-06 03:36:35-05 Webserver starting on 4005
21-03-06 03:36:35-05 [..] Initial setup: Creating objects (Account #1 and Limbo room) ...
21-03-06 03:36:35-05 [..] Initial setup: Creating default channels ...
21-03-06 03:36:35-05 [..] Initial setup: Running at_initial_setup() hook.
21-03-06 03:36:36-05 [..] Initial setup: Gathering static resources using 'collectstatic'
21-03-06 03:36:36-05 
21-03-06 03:36:36-05 0 static files copied to 'D:\muddev\hecate\web\static', 156 unmodified.
21-03-06 03:36:36-05 [..] Initial setup complete. Restarting Server once.
21-03-06 03:36:36-05 Evennia Server successfully started.
21-03-06 03:36:37-05 [..] Server disconnected from the portal.
21-03-06 03:36:37-05 Main loop terminated.
21-03-06 03:36:37-05 Server Shut Down.
21-03-06 03:36:37-05 Server Shut Down.
21-03-06 03:36:37-05 Loading d:\muddev\evennia\evennia\server\server.py...
21-03-06 03:36:38-05 Loaded.
21-03-06 03:36:38-05 twistd 20.3.0 (d:\muddev\evenv\scripts\python.exe 3.7.4) starting up.
21-03-06 03:36:38-05 reactor class: twisted.internet.selectreactor.SelectReactor.
21-03-06 03:36:38-05 Webserver starting on 4005
21-03-06 03:36:38-05 Evennia Server successfully restarted in 'reset' mode.
21-03-06 03:38:02-05 [SS] Authentication Success: Kovitikus(account 1) (IP: 127.0.0.1).
21-03-06 03:38:02-05 [..] Logged in: Kovitikus(account 1) 127.0.0.1 (1 session(s) total)
```

**Comment by kovitikus** [comment]
This bug seems closed now. I was able to destroy `evennia.db3` and execute `evennia migrate` without issues from superuser object creation. 

My custom `at_initial_setup` enhancements (changing `Limbo` to `Default Home`) and setting `dbref #2`'s `desc` attribute to an explanation of the room.
