### ISSUE TITLE
Refactor Behavior for Exit Traversal

### ISSUE THREAD

**Issue by kovitikus** [kovitikus/hecate#39]
I'm not sure if I should dump this stuff into a handler or not.

I need to look through the Character typeclass hooks for `announce_move_to` and `announce_move_from` and see if I can rewrite it into something more comprehensive.

I also want to consider adding dedicated attributes for certain aspects.

Right now, the exit name is what Evennia looks for when a player types the command to go through. I want that to remain the same name as the exit object; i.e. `a faded green door`, but also want to maintain cardinal directions.I currently use the cardinal direction as the exit name and tack on door to the alias.

This is code I wrote years ago when first starting this project, so I doubt there's much to salvage in its current form.

**Comment by kovitikus** [comment]
I've made some tremendous progress on this issue so far.

There's still a few things that remain to be done before I can even test these changes.

I need to rewrite `announce_move_to` hook in the `Character` typeclass.

I then need to evaluate my starting world and ensure the exits are properly set with exit type tags.

**Comment by kovitikus** [comment]
When attempting to go north through a door.
```
Traceback (most recent call last):
  File "d:\muddev\evennia\evennia\commands\cmdhandler.py", line 644, in _run_command
    ret = cmd.func()
  File ".\travel\travel_cmds.py", line 111, in func
    success = caller.travel.traverse_cardinal_exit(direction)
  File ".\travel\travel_handler.py", line 53, in traverse_cardinal_exit
    self.travellers = [owner, *list(owner.db.followers)]
TypeError: 'NoneType' object is not iterable

An untrapped error occurred.
(Traceback was logged 21-03-10 19:50:28-05).
```

**Comment by kovitikus** [comment]
Everything is working pretty great now. There were surprisingly few issues that surfaced. Some were my failed logic and others were simple mistakes.

I still need to get the travel_cmdset onto the character.

I also need to clean up some of the strings, specifically the location_summary result.

```
You arrive at Main Office(#4).Kovitikus(#1) a mahogany door(#6) heading north
```

**Comment by kovitikus** [comment]
Ok, I have the exits working out pretty well. All that's left to do now is some tweaking and eventual bug fixes that pop up. This issue is considered closed for the time being. I need some new rooms to test exits on and the easiest way to do that is to go back to the InstanceHandler.

![2 exits functional in the same room](https://i.imgur.com/q4gobGC.png)

**Comment by kovitikus** [comment]
![char walk](https://i.imgur.com/y1oiZWg.png)

**Comment by kovitikus** [comment]
![multiple char movement appearance](https://i.imgur.com/F6WBRvd.png)
