### ISSUE TITLE
Instances won't clean themselves up.

### ISSUE THREAD

**Issue by kovitikus** [kovitikus/hecate#45]
Something about the changes I made in 85af7ae to the hooks that call the instance cleanup isn't being triggered. It may not be triggered by either the enter or exit instance methods. Investigate and address.

**Comment by kovitikus** [comment]
The issue was that I was still checking for the tag category as exits rather than rooms in the at_object_receive/leave hooks.

That's working now, but it turns out that destroying the room as soon as the object leaves kills the character's movement hooks, because they rely on checking for the source room.

> 21-04-20 21:05:02-04 [::] Traceback (most recent call last):
21-04-20 21:05:02-04 [::]   File "d:\muddev\evennia\evennia\objects\objects.py", line 831, in move_to
21-04-20 21:05:02-04 [::]     source_location.at_object_leave(self, destination)
21-04-20 21:05:02-04 [::]   File "D:\muddev\hecate\rooms\rooms.py", line 42, in at_object_leave
21-04-20 21:05:02-04 [::]     self.room.set_room_vacant(moved_obj)
21-04-20 21:05:02-04 [::]   File "D:\muddev\hecate\rooms\room_handler.py", line 81, in set_room_vacant
21-04-20 21:05:02-04 [::]     zone_occupant_list = list(zone_ledger_uid['occupants'])
21-04-20 21:05:02-04 [::] TypeError: 'NoneType' object is not subscriptable
21-04-20 21:05:02-04 [::] Traceback (most recent call last):
21-04-20 21:05:02-04 [::]   File "d:\muddev\evennia\evennia\objects\objects.py", line 839, in move_to
21-04-20 21:05:02-04 [::]     self.announce_move_from(destination, **kwargs)
21-04-20 21:05:02-04 [::]   File ".\characters\characters.py", line 128, in announce_move_from
21-04-20 21:05:02-04 [::]     if self.travel.travel_one_way(): # If the player is teleported.
21-04-20 21:05:02-04 [::]   File ".\travel\travel_handler.py", line 207, in travel_one_way
21-04-20 21:05:02-04 [::]     if not hasattr(self.exit_obj, 'destination'):
21-04-20 21:05:02-04 [::]   File "d:\muddev\evennia\evennia\utils\idmapper\models.py", line 200, in fget
21-04-20 21:05:02-04 [::]     return _get_foreign(cls, fieldname)
21-04-20 21:05:02-04 [::]   File "d:\muddev\evennia\evennia\utils\idmapper\models.py", line 126, in _get_foreign
21-04-20 21:05:02-04 [::]     "Cannot access %s: Hosting object was already deleted." % fname
21-04-20 21:05:02-04 [::] django.core.exceptions.ObjectDoesNotExist: Cannot access db_destination: Hosting object was already deleted.

> 21-04-20 21:07:27-04 [::] Traceback (most recent call last):
21-04-20 21:07:27-04 [::]   File "d:\muddev\evennia\evennia\objects\objects.py", line 831, in move_to
21-04-20 21:07:27-04 [::]     source_location.at_object_leave(self, destination)
21-04-20 21:07:27-04 [::]   File "D:\muddev\hecate\rooms\rooms.py", line 42, in at_object_leave
21-04-20 21:07:27-04 [::]     self.room.set_room_vacant(moved_obj)
21-04-20 21:07:27-04 [::]   File "D:\muddev\hecate\rooms\room_handler.py", line 81, in set_room_vacant
21-04-20 21:07:27-04 [::]     zone_occupant_list = list(zone_ledger_uid['occupants'])
21-04-20 21:07:27-04 [::] TypeError: 'NoneType' object is not subscriptable
