### ISSUE TITLE
CurrencyHandler copper_to_coin_dict unpacking failure.

### ISSUE THREAD

**Issue by kovitikus** [kovitikus/hecate#49]
For some reason the 3rd coin in the test_item_handler fails to convert the copper value into a coin_dictionary via the CurrencyHandler's `copper_to_coin_dict` method.

***

**test_item_handler.py**

```python
from evennia.utils.create import create_object
from misc.test_resources import HecateTest

class TestItemHandler(HecateTest):
    def setUp(self):
        super().setUp()
        self.obj_loc = self.room1
        coin1_value = 328982 # (0 plat, 0 gold, 328 silver, 982 copper)
        coin2_value = 897324 # (0 plat, 0 gold, 897 silver, 324 copper)
        # Total value of coin1 + coin2 = 1,226,306 (0 plat, 1 gold, 226 silver, 306 copper)

        coin3_value = 549843 # (0 plat, 0 gold, 549 silver, 843 copper)

        coin1 = create_object(typeclass="items.objects.Coin", key="coin1", location=self.obj_loc)
        coin1.db.coin = coin1.currency.copper_to_coin_dict(coin1_value)

        coin2 = create_object(typeclass="items.objects.Coin", key="coin2", location=self.obj_loc)
        coin2.db.coin = coin2.currency.copper_to_coin_dict(coin2_value)

        coin3 = create_object(typeclass="items.objects.Coin", key="coin3", location=self.obj_loc)
        coin3.db.coin = coin3.currency.copper_to_coin_dict(coin3_value)

        self.two_coin_groupables = [coin1, coin2]
        self.three_coin_groupables = [coin1, coin2, coin3]

    def test_group_objects(self):
        final_msg = self.char1.item.group_objects(self.two_coin_groupables, self.obj_loc)
        self.assertEqual("You group together coin1 and coin2.", final_msg)

        final_msg = self.char1.item.group_objects(self.three_coin_groupables, self.obj_loc)
        self.assertEqual("You group together coin1, coin2, and coin3.", final_msg)
    
    def test_group_coins(self):
        qty_group_obj = self.char1.item._group_coins(self.two_coin_groupables, self.obj_loc)
        self.assertTrue(qty_group_obj.is_typeclass("items.objects.QuantityGroup", exact=True))
        self.assertEqual(0, qty_group_obj.db.coin['plat'])
        self.assertEqual(1, qty_group_obj.db.coin['gold'])
        self.assertEqual(226, qty_group_obj.db.coin['silver'])
        self.assertEqual(306, qty_group_obj.db.coin['copper'])
        self.assertEqual('a pile of coins', qty_group_obj.key)
        self.assertEqual(self.obj_loc, qty_group_obj.location)
```

***

**Unit Test Ouput**

```
(evenv) D:\muddev\hecate>evennia test --settings settings.py items
Using settings file 'settings.py' (server.conf.settings).

    TESTING: Using specified settings file 'server.conf.settings'.

    OBS: Evennia's full test suite may not pass if the settings are very
    different from the default (use 'evennia test evennia' to run core tests)

Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.E
======================================================================
ERROR: test_group_objects (hecate.items.test_item_handler.TestItemHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\muddev\hecate\items\test_item_handler.py", line 31, in test_group_objects
    final_msg = self.char1.item.group_objects(self.three_coin_groupables, self.obj_loc)
  File "D:\muddev\hecate\items\item_handler.py", line 223, in group_objects
    qty_msg = self._group_quantity_objects(qty_groupables, obj_loc)
  File "D:\muddev\hecate\items\item_handler.py", line 256, in _group_quantity_objects
    self._group_coins(coin_groupables, obj_loc)
  File "D:\muddev\hecate\items\item_handler.py", line 279, in _group_coins
    total_copper += obj.currency.coin_dict_to_copper(obj.db.coin)
  File "D:\muddev\hecate\characters\currency_handler.py", line 171, in coin_dict_to_copper
    return self.convert_coin_type(**coin_dict)
TypeError: convert_coin_type() argument after ** must be a mapping, not NoneType

----------------------------------------------------------------------
Ran 2 tests in 1.273s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by kovitikus** [comment]
The problem was that the coins are being deleted in the first test of the coins within `test_group_objects()`. I'm then ATTEMPTING to reuse the same coin objects for the 2nd part of the test, but they no longer exist. coin1 and coin2 are only recreated by setUp() between tests.

The solution is to simply create a separate test for each type of test for this method. 
`test_group_objects1()`
`test_group_objects2()`
etc
